In [ ]:
"""
 - ndarray is the main data structure in numpy
 
"""
import numpy as np
a = np.array(
    [
        [1, 2, 3], 
        [4, 5, 6]
    ],
    dtype=np.int32
)
print(a)
print(a.shape) #Shape is the # of rows and columns (2, 3)
print(a.ndim) #Prints the rank of this matrix, in other words, the number of domensions, which can be found by the level of nesting of the arrays. In this case, it's 2
print(a.size) #Total number of elements in the array
print(a.dtype) #Data type in the array, which is always homogenous, in this case, it's an integer with a size of 32 bits, or 4 bytes
print(a.itemsize) #Size in bytes of each element in the array
print(a.nbytes) #Total size of the array in bytes

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int32
4
24


In [7]:
print(np.zeros((3, 4), dtype=np.float32))#This function will create an array with the shape that was passed in as a parameter, and fill it with 0s.
# The array will have all of its values be 32 bit, or 4 byte float
print(np.ones((2, 2))) #Same thing, pretty much, but with 1s instead of 0s
print(np.full((2, 3), fill_value=7)) #Creates an array with the specified shape, and fills it with the fill_value
np.empty((1000,)) #Quickly creates an uninitialized array     
print(np.arange(0, 10, 2)) #creates an array with starting value and finishing value, and every number in between by counting with the specified step size
# Does not include the ending value      
print(np.linspace(0.0, 1.0, 5)) #creates an array with the starting and end values specified, and the total number of elements (both the start and end included) .
#The remaining elements are equal intervals between the start and the end

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Dtype control and inference:
np.array([1, 2, 3], dtype=np.float32) #This is how you would set the data type explicitly
np.asarray([1, 2, 3]) #The asarray method normally converts other iterables into numpy arrays, but if you use it on a numpy array that already exists, 
#keeping the elements and data type the same, then it will simply give you a view of that array instead of creating a copy, making it memory efficient
np.array([True, False], dtype=np.int8) #In this method, we're using the dtype attribute to cast the boolean list into an array of 8 bit integers

In [ ]:
A = np.arange(12) #Generates an array of 
print(A)
B = A.reshape(3, 4, order="C") #Reshapes the array into a 3 x 4 array ordered by row major order
print(B)
C = np.arange(1, 13).reshape(3, 4, order="F") # this one creates a similar array but organized by column major order instead of row major order, which is the default
print(C)
np.set_printoptions(precision=3,  suppress=True) 
# ^Options for printing out all these arrays. precision refers to the number of digits of precision for a float output, which has a default value of 8
# If suppress is registered as true, then floating point numbers will always used the fix notation. 
# If set to false, then they will use scientific notation for larger or smaller values
print(A)
print(a[:2, :3]) #Sliced the 2D array by getting rid of the third row and the fourth column

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Drills
#Create a 3×5 array of float32 ones. Report shape, ndim, size, dtype, itemsize, nbytes.
A = np.ones((3, 5), dtype=np.float32)
info = f"""
shape: {A.shape}
# of dimensions: {A.ndim}
size: {A.size}
type: {A.dtype}
item_size: {A.itemsize}
total # of bytes: {A.nbytes}
"""
print(info)
#Build np.arange(36) and reshape to 3×3×4. Verify that size is unchanged.
B = np.arange(36).reshape(3, 3, 4)
print(B)
#Create a length-10 vector from 0 to 1 inclusive with equal spacing. Confirm first, middle, last values.
C = np.linspace(0, 1, 10)
print(C)
#Given [[1,2,3],[4,5,6]], build int8 and float32 versions. Compare nbytes.
D = np.array([[1,2,3],[4,5,6]], dtype=np.int8)
E = np.array([[1,2,3],[4,5,6]], dtype=np.float32)
print(f"D: {D.nbytes}, E: {E.nbytes}")
#Create a 1000-element array with empty, then safely fill it with index values.
F = np.empty(1000, dtype=np.int32)
np.copyto(F, np.arange(F.size, dtype=F.dtype))
assert F[0] == 0 and F[-1] == 999
#Produce two 3×3 arrays using order="C" and order="F". Print strides and explain the difference in one line.
G = np.arange(9).reshape(3, 3, order="C")
H = np.arange(10, 19).reshape(3, 3, order="F")
print(G.strides)
print(H.strides)
#Show how to convert a Python list of booleans to int8 and back to bool.
I = np.array([True, False, True], dtype=np.int8)
print(I)
print(I.astype(bool))
#Set printoptions to show 2 decimals and suppress scientific notation, then print a small random array.
np.printoptions(precision=2, suppress=True)


shape: (3, 5)
# of dimensions: 2
size: 15
type: float32
item_size: 4
total # of bytes: 60

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
[0.    0.111 0.222 0.333 0.444 0.556 0.667 0.778 0.889 1.   ]
D: 6, E: 24
(24, 8)
(8, 24)
[1 0 1]
[ True False  True]
