In [ ]:
import numpy as np
np.array([1, 2, 3], dtype=None, copy=True, order='K', ndmin=0) #Always constructs
#copy = True means that this array uses a new memory buffer, False means that it reuses freed memory, 

#copy means that it returns a view but that any required changes (dtype cast, order change, shape fix) will create a new copy regardless

#order refers to the way that the elements are stored in memory
#'C': row-major contiguous.
#'F': column-major contiguous.
#'A': like Fortran if the input is Fortran-contiguous, else C.
#'K' (default): “keep” as close as possible to the input’s memory layout; makes minimal changes.

#Note: For 1-D arrays, order has no practical effect on contiguity.
#ndmin: Minimum number of dimensions. If the input has fewer, prepend size-1 axes on the left.
#For a column vector, reshape explicitly: np.array([1,2,3], ndmin=2).T → (3,1) or use .reshape(-1,1).

np.array([1,2,3], dtype=np.float32) #control dtype
np.array(np.ones((2,3), order='F'), copy=False)  #may keep Fortran order due to 'K'
np.array([1,2,3], ndmin=2) #shape (1,3)
np.array([[1,2],[3,4]], order='F') #make Fortran-contiguous copy

In [ ]:
import numpy as np
np.asarray([1, 2, 3], dtype=None, order=None, like=None) #avoid copy if possible
#if like is true, then this method returns the result in the form of an array that comes from another framework if that framework implements __array_function__
#If like is a NumPy array or None → normal NumPy result.

np.asanyarray([1, 2, 3], dtype=None, order=None) #preserves subclasses
#Takes in some kind of iterable, and if the object passed in is some kind of ndarray subclass, then it will be returned as it is

np.frombuffer([1, 2, 3], dtype=float, count=-1, offset=0) #Not an actual buffer or anything
#interprets a buffer and turns it into a 1d numpy array, count and offset control how much is read

In [ ]:
buf = b'\x00\x01\x02\x03' #view over bytes (often read-only)
v = np.frombuffer(buf, dtype=np.uint8) #view; modifying buf may change v
v_copy = v.copy() #detach if needed
print(v)

[0 1 2 3]


In [6]:
fromitr = np.fromiter((1, 2, 3, 4, 5, 6), dtype=np.int32, count=-1) #stream into 1-D efficiently
print(fromitr)

[1 2 3 4 5 6]


In [ ]:
a = np.arange(6, dtype=np.float32).reshape(2, 3, order="F")
e = np.empty_like(a) #allocates fast buffer matching a’s shape, dtype, and memory order. Values are unspecified.
print(e)
z = np.zeros_like(a) #returns an array of zeros with a’s shape, dtype, and order
print(z)
o = np.ones_like(a) #returns an array of ones with a’s shape, dtype, and order.
print(o)
f = np.full_like(a, fill_value=-1.5) #returns an array filled with v, cast to a.dtype, with a’s shape and order.
print(f)

[[0. 2. 4.]
 [1. 3. 5.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[-1.5 -1.5 -1.5]
 [-1.5 -1.5 -1.5]]


In [13]:
#Allocates an array but does not set values. Contents are arbitrary bytes (“garbage”). Fastest. Never read before you write
a = np.empty((2,3), dtype=np.float32) 

#Allocates and fills with 0. Safe default, slightly slower than empty
z = np.zeros((2,3), dtype=np.float32)

#Allocates and fills with 1. Useful for biases, masks, or baselines.
o = np.ones((2,3), dtype=np.int32)

#Allocates and fills with a constant. fill_value is cast to dtype.
f = np.full((2,3), -1.5, dtype=np.float32)

'''
 - Use empty only when you immediately write every element.
 - Use zeros/ones when you need known initialization.
 - Use full for any other constant fill.
 - Prefer explicit dtype to avoid silent float64.
'''

'\n - Use empty only when you immediately write every element.\n - Use zeros/ones when you need known initialization.\n - Use full for any other constant fill.\n - Prefer explicit dtype to avoid silent float64.\n'

In [ ]:
np.empty((3, 3), dtype=float, order='C') # ast, garbage values
np.zeros((3, 3), dtype=float, order='C')
np.ones((3, 3), dtype=float, order='C')
np.full((3, 3), 5, dtype=None, order='C')

In [ ]:
#Generates num values whose exponents are evenly spaced from start to stop on a log scale of given base. 
#It returns base**linspace(start, stop, num). Endpoints are included by default.
X = np.logspace(0, 3, num=4, base=10, dtype=np.float32) # 10^0, 10^1, 10^2, 10^3
print(X)

#Generates a geometric progression from start to stop with a constant ratio between terms. 
# Equivalent to exp(linspace(log(start), log(stop), num)) for positive reals. 
# Endpoints included. Use positive start and stop for real outputs.
Y = np.geomspace(1, 1000, num=4, dtype=np.float32)  #1, 1*10, 10 * 10, 10 * 10 * 10
print(Y)

[   1.   10.  100. 1000.]
[   1.   10.  100. 1000.]


In [2]:
import numpy as np
#Creates a 2-D array with ones on the k-th diagonal and zeros elsewhere. 
# M defaults to N. k>0 → superdiagonal. 
# k<0 → subdiagonal.
A = np.eye(3, 4, k=1, dtype=int)
print(f"\n{A}")

#Square identity matrix (same as np.eye(n) with k=0).
B = np.identity(3, dtype=int)
print(B)

#Two modes. 
#If v is 1-D, returns a 2-D array with v on the k-th diagonal. 
#If v is 2-D, returns the k-th diagonal of v as 1-D.
C = np.diag([4,5,6], k=0) #np.diag(v, k=0)
#v is some array like input. If that input is 1d, then this function returns a 2d array with v on the kth diagonal
#if v is 2d, then the function returns a 1d array with the kth diagonal of v.
#k has a default value of 0, and if k > 0, then we're looking at the kth superdiagonal (above the main diagonal)
#if k < 0, then we're looking at the kth subdiagonal (below the main diagonal)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int32)
D = np.diag(arr, k=0)
print(C)
print(D)

#np.tri(N, M=None, k=0, dtype=float)
#Lower-triangular mask (ones on and below the k-th diagonal, zeros above). M defaults to N.
E = np.tri(3, 5, k=1, dtype=int) #Triangular mask of 1s on and below the kth diagonal
#N is the number of rows, M is the number of columns
print(E)

#np.tril(A, k=0) A is the numpy array, and k represents the diagonal
#This method keeps the kth diagonal and all the diagonals below it, and turns everything else into 0s
sample = np.arange(1,10).reshape(3,3)
F = np.tril(sample, k=0)
print(F)

#np.triu(A, k=0) A is the nnumpy array, and k represents the diagonal
#Keeps the upper triangle of A (on and above the k-th diagonal). Zeros out elements below it.
sample = np.arange(1,10).reshape(3,3)
G = np.triu(sample, k=0)
print(G)


[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[4 0 0]
 [0 5 0]
 [0 0 6]]
[1 5 9]
[[1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]
[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [ ]:
import numpy as np

#np.meshgrid(x, y, indexing='xy')
#Takes 1-D coordinate vectors and returns 2-D coordinate matrices. 
# Default 'xy': rows follow y, columns follow x. Use 'ij' for matrix indexing.
x = np.array([0, 1, 2])
y = np.array([10, 20])
X, Y = np.meshgrid(x, y, indexing='xy')
print(X)
print(X.shape)
print(Y)
print(Y.shape)
X, Y = np.meshgrid(x, y, indexing='ij')
print(X)
print(X.shape)
print(Y)
print(Y.shape)

[[0 1 2]
 [0 1 2]]
(2, 3)
[[10 10 10]
 [20 20 20]]
(2, 3)
[[0 0]
 [1 1]
 [2 2]]
(3, 2)
[[10 20]
 [10 20]
 [10 20]]
(3, 2)


In [ ]:
#np.mgrid[a:b:step, ...]
#Dense grid via slice notation. Returns full coordinate matrices like meshgrid('ij'). Integer step → stop is exclusive. 
# Complex step (e.g., 5j) → like linspace with that many points.
I, J = np.mgrid[0:3, 10:30:10]
print(I)
print(I.shape)
print(J)
print(J.shape)

[[0 0]
 [1 1]
 [2 2]]
(3, 2)
[[10 20]
 [10 20]
 [10 20]]
(3, 2)


In [7]:
#np.ogrid[a:b:step, ...]
#“Open” grid: returns broadcastable coordinate vectors instead of full matrices. 
# Memory-light. Shapes are expanded with size-1 axes.
i, j = np.ogrid[0:3, 10:30:10]
print(i)
print(j)
R = (i**2 + j**2)**0.5

[[0]
 [1]
 [2]]
[[10 20]]


In [10]:
#np.indices(dimensions)
#Index grid of given shape. Returns one integer matrix per axis stacked on axis 0.
idx = np.indices((3, 2))
print(idx)
print("\n")
I, J = idx[0], idx[1]
print(I)
print("\n")
print(J)

[[[0 0]
  [1 1]
  [2 2]]

 [[0 1]
  [0 1]
  [0 1]]]


[[0 0]
 [1 1]
 [2 2]]


[[0 1]
 [0 1]
 [0 1]]
