In [1]:
import numpy as np
# a dtype is for determining things like storage and semantics per element - kind, width, and byte order
# for inspecting things:
A = np.array(
    [
        [1, 2, 3], 
        [4, 5, 6]
    ]
)
print(f"{A.dtype}, {A.itemsize}, {A.nbytes}, {A.strides}")

int64, 8, 48, (24, 8)


In [4]:
# For information
print(np.iinfo(np.int32))
print(np.finfo(np.float32))

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------



In [ ]:
#booleans
B = np.array([True, False, True], dtype=np.bool_)
print(f"{B}, {B.itemsize}") # Booleans are stored as one byte

#Integers
C = np.array([1, 2, 3, 4, 5, 6], dtype=np.int8)
D = np.array([1, 2, 3, 4, 5, 6], dtype=np.int16)
E = np.array([1, 2, 3, 4, 5, 6], dtype=np.int32)
F = np.array([1, 2, 3, 4, 5, 6], dtype=np.int64)
print(f"{C}, {C.itemsize}")
print(f"{D}, {D.itemsize}")
print(f"{E}, {E.itemsize}")
print(f"{F}, {F.itemsize}")

[ True False  True], 1
[1 2 3 4 5 6], 1
[1 2 3 4 5 6], 2
[1 2 3 4 5 6], 4
[1 2 3 4 5 6], 8


In [ ]:
#Unisigned Integers
# data type in computer science that stores only non-negative whole numbers (zero and positive numbers), 
# with a range that extends from 0 up to a maximum value determined by the number of bits used
G = np.array([1, 2, 3, 4, 5, 6], dtype=np.uint8)
H = np.array([1, 2, 3, 4, 5, 6], dtype=np.uint16)
I = np.array([1, 2, 3, 4, 5, 6], dtype=np.uint32)
J = np.array([1, 2, 3, 4, 5, 6], dtype=np.uint64)
print(f"{G}, {G.itemsize}")
print(f"{H}, {H.itemsize}")
print(f"{I}, {I.itemsize}")
print(f"{J}, {J.itemsize}")

[1 2 3 4 5 6], 1
[1 2 3 4 5 6], 2
[1 2 3 4 5 6], 4
[1 2 3 4 5 6], 8


In [ ]:
#Default for float is 64, but the ML default is 32
K = np.array([1, 2, 3, 4, 5], dtype=np.float16)
L = np.array([1, 2, 3, 4, 5], dtype=np.float32)
M = np.array([1, 2, 3, 4, 5], dtype=np.float64)
print(K)
print(L)
print(M)

[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


In [13]:
#Complex
N = np.array([1 + 2j], dtype=np.complex64)
O = np.array([1 + 2j], dtype=np.complex128)
print(N.itemsize)
print(O.itemsize)

8
16


In [ ]:
#use explicit definition of the dtype during array creation
# Common traps default to float64: linspace, ones, randn-style outputs, Python floats.
rng = np.random.default_rng(0) #This method create a new generator instance with the seed 0. It gives you an isolated, reproducible random stream 
rng.standard_normal(1000, dtype=np.float32) #Draws 1,000 samples from a standard normal 𝑁(0,1) using that generator. 
# Returns a float32 array directly (no post-cast)

In [15]:
#Casting - Conversion vs reinterpreting
#Convert values: astype(new_dtype, copy=False); returns view if already same dtype.
#Reinterpret bytes: .view(new_dtype); no value change, only how bytes are read.

P = np.array([1, 2, 3, 4, 5, 6], dtype=np.int64)
Q = P.astype(np.float32)
R = P.view(np.uint32)
print(P)
print(Q)
print(R)
#Safe/unsafe casting flags appear in many APIs: 'no' < 'equiv' < 'safe' < 'same_kind' < 'unsafe'.
#Check feasibility: np.can_cast(from_dtype, to_dtype, casting='safe').
print(np.can_cast(np.uint32, np.bool_))

[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]
[1 0 2 0 3 0 4 0 5 0 6 0]
False


In [ ]:
#Boolean Behavior
#Comparisons yield bool arrays.
#In arithmetic, bool → integers 0/1, then usual promotion.
S = np.array([True, False], dtype=bool)
print((S + 2).dtype ) #The bool array is converted to the type int64, and then 2 is added to the array.
#It becomes 1, 0, 2, and since 2 is a python int, the array type defaults to np.int_, which is int64 on 64 bit systems and int32 on 32 bit systems
print((S & (S==1)).dtype) #In this one, it's converted to booleans, and the type is displayed

int64
bool


In [ ]:
#NaN/±inf exist only in floating and complex dtypes.
#Introducing np.nan or np.inf into integer arrays forces upcast to float.
#NaN means "Not a Number", and inf is infinity, which can be +inf or -inf
T = np.array([1, 2, 3], dtype=np.int32)
T = T.astype(np.float32)
T[0] = np.nan
#np.result_type(*args): “If I did an elementwise op on these, what dtype would NumPy use?”
#np.promote_types(t1, t2): “Smallest dtype both can be safely cast to.”

#Same kind → widen width: int32 + int64 -> int64, float32 + float64 -> float64.
#Integer with float → float, usually float64 if a Python float is involved.
#Keep float32 by avoiding Python float: use np.float32(1.0) or arrays of float32.
#Any complex operand → complex; real part and imag part width follow the widest real.
#Signed + unsigned → a wider integer if it can represent both ranges; if not, expect upcast to float or object. Avoid mixing signed and unsigned.
#Array + scalar: Python scalar types influence promotion (1.0 is 64-bit). Prefer NumPy scalars (np.float32(1)).

#Examples to memorize
np.ones(3, np.float32) + np.ones(3, np.float32)         # float32
np.ones(3, np.float32) + 1                              # float32 (int -> safely cast)
np.ones(3, np.float32) + 1.0                            # often float64 (Python float)
np.array([1], np.int32) + np.array([1], np.float32)     # often float64
np.array([1], np.int32) + np.array([1], np.int64)       # int64
np.array([1], np.uint8) + np.array([255], np.uint8)     # uint8 overflow wraps (mod 256)

In [ ]:
#Integers wrap on overflow; no warning by default. Use a wider dtype if near limits, or switch to float.